name = "tunestream"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "tunestream-db"
database_id = "3d74e41f-da32-4c29-8063-dd5596e970c5" # User will need to replace this after creating DB on dashboard or CLI
